site_name: ckanext-selfinfo
site_url: https://datashades.github.io/ckanext-selfinfo/

repo_url:  https://github.com/DataShades/ckanext-selfinfo

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Requirements: requirements.md
  - Installation: installation.md
  - Config Settings: config_settings.md
  - Configuration:
    - Secure URL and Action: configuration/secure_url_and_action.md
    - Unique Redis key: configuration/unique_redis_key_per_portal_instance.md
    - Enable Errors: configuration/errors.md
    - GIT Info: configuration/git_info.md
    - Solr Schema: configuration/solr_schema.md
    - Categories: configuration/categories.md
  - CLI: cli.md
  - Profiles:
    - Overview: profiles/overview.md
    - Cron Based:
      - Selfinfo custom Redis key: profiles/redis_key.md
      - Selfinfo internal IP Redis key (experimental):
        - Overview:  profiles/duplicated_env.md
        - Shared Categories: profiles/shared_categories.md
  - Extending Selfinfo: extending/overview.md
  - Selftools:
    - Overview: selftools/overview.md
    - Confiruation: selftools/configuration.md
    - Categories:
      - Solr: selftools/categories/solr.md
      - DB: selftools/categories/db.md
      - Redis: selftools/categories/redis.md
      - Config: selftools/categories/config.md
    - Config Settings: selftools/config_settings.md
    - Extending Selftools: selftools/extending_selftools.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences